In [1]:
import pandas as pd
df = pd.read_json("../DATA COLLECTION AND WEB SCRAPPING(JUMIA)/products.json")
df.head()

                                name     price old_price
0           ADIDAS Top quality Samba  ₦ 36,575  ₦ 40,000
1  ADIDAS Top quality Samba sneakers  ₦ 35,150  ₦ 38,000
2          ADIDAS  Mix Ad 2 sneakers  ₦ 39,000  ₦ 40,000
3  ADIDAS All black quality sneakers  ₦ 40,000       NaN
4  ADIDAS Deep gray quality sneakers  ₦ 40,000       NaN

In [3]:
import requests
from bs4 import BeautifulSoup

url = "https://www.jumia.com.ng/adidas/?q=adidas+sneakers#catalog-listing"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")


products=soup.find_all("a", class_="core")

Products_Data = []

for product in products:
    name = product.find("h3", class_="name")
    price = product.find("div", class_="prc")
    oldp = product.find("div", class_="old")

    name = name.get_text(strip=True)
    price = price.get_text(strip=True)

    if oldp:
        old_price = oldp.get_text(strip=True)
    else:
        old_price = None

    product_data ={
        "name": name,
        "price": price,
        "old_price": old_price
    }
    

    Products_Data.append(product_data)
print("Products_Data=",Products_Data)

Products_Data= [{'name': 'ADIDAS Originals Sneakers Superstar', 'price': '₦ 15,350', 'old_price': '₦ 153,500'}, {'name': 'ADIDAS Originals Sneakers Superstar Slip On W', 'price': '₦ 13,195', 'old_price': '₦ 208,542'}, {'name': 'ADIDAS Tensaur Hook And Loop Shoes Unisex', 'price': '₦ 11,070', 'old_price': '₦ 73,800'}, {'name': 'ADIDAS Levato - Women', 'price': '₦ 18,675', 'old_price': '₦ 124,500'}, {'name': 'ADIDAS Tensaur Hook And Loop Shoes Unisex', 'price': '₦ 11,070', 'old_price': '₦ 73,800'}, {'name': 'ADIDAS Breaknet Lifestyle Court Two-Strap Hook-and-Loop Shoes Unisex', 'price': '₦ 13,770', 'old_price': '₦ 91,800'}, {'name': 'ADIDAS Grand Court Elastic Lace And Top Strap Shoes Unisex', 'price': '₦ 102,600', 'old_price': None}, {'name': 'ADIDAS Levato - Women', 'price': '₦ 18,675', 'old_price': '₦ 124,500'}, {'name': 'ADIDAS Grand Court X Marvel Spider-Man Shoes Kids', 'price': '₦ 14,265', 'old_price': '₦ 95,100'}, {'name': 'ADIDAS Advantage Lifestyle Court Two Hook-and-Loop Shoes Kids', 'price': '₦ 14,265', 'old_price': '₦ 95,100'}, {'name': 'ADIDAS ADVANTAGE SHOES WOMEN', 'price': '₦ 25,080', 'old_price': '₦ 167,200'}, {'name': 'ADIDAS Tensaur Hook And Loop Shoes Unisex', 'price': '₦ 11,070', 'old_price': '₦ 73,800'}, {'name': 'ADIDAS Breaknet Lifestyle Court Two-Strap Hook-and-Loop Shoes Unisex', 'price': '₦ 13,770', 'old_price': '₦ 91,800'}, {'name': 'ADIDAS Top quality Samba', 'price': '₦ 36,575', 'old_price': '₦ 40,000'}, {'name': 'ADIDAS  Mix Ad 2 sneakers', 'price': '₦ 39,000', 'old_price': '₦ 40,000'}, {'name': 'ADIDAS Top quality Samba sneakers', 'price': '₦ 35,150', 'old_price': '₦ 38,000'}, {'name': 'ADIDAS Advantage K unisex sneakers', 'price': '₦ 55,000', 'old_price': None}, {'name': 'ADIDAS All black quality sneakers', 'price': '₦ 40,000', 'old_price': None}, {'name': "ADIDAS Women's Run 60s 3.0 Shoes", 'price': '₦ 54,900', 'old_price': '₦ 71,999'}, {'name': 'ADIDAS BreezeWalk W WOMEN', 'price': '₦ 22,540', 'old_price': '₦ 112,700'}, {'name': 'ADIDAS Originals Sneakers Superstar Women', 'price': '₦ 21,366', 'old_price': '₦ 225,234'}, {'name': 'ADIDAS Top quality Samba flower', 'price': '₦ 37,050 - ₦ 38,000', 'old_price': '₦ 40,000'}, {'name': 'ADIDAS Unisex-Child Breaknet 2.0K Sneakers', 'price': '₦ 44,000', 'old_price': '₦ 58,999'}, {'name': 'ADIDAS Unisex Kids’ Sneakers', 'price': '₦ 45,000', 'old_price': '₦ 69,300'}, {'name': 'ADIDAS Quality multicolor sneakers', 'price': '₦ 45,000', 'old_price': '₦ 60,000'}, {'name': 'ADIDAS Grand Court Lifestyle Hook And Loop Shoes Unisex', 'price': '₦ 11,405 - ₦ 82,800', 'old_price': '₦ 82,800'}, {'name': 'ADIDAS Originals Sneakers Kids Superstar Cf C', 'price': '₦ 23,790', 'old_price': '₦ 135,455'}, {'name': 'ADIDAS Originals Sneakers Kids Superstar Cf I', 'price': '₦ 17,377', 'old_price': '₦ 115,847'}, {'name': 'ADIDAS Breaknet Lifestyle Court Two-Strap Hook-and-Loop Shoes Unisex', 'price': '₦ 13,770', 'old_price': '₦ 91,800'}, {'name': 'ADIDAS black and white quality sneakers', 'price': '₦ 40,000', 'old_price': None}, {'name': 'ADIDAS Deep gray quality sneakers', 'price': '₦ 40,000', 'old_price': None}, {'name': 'ADIDAS Off white quality sneakers', 'price': '₦ 40,000', 'old_price': None}]

In [4]:
import requests
from bs4 import BeautifulSoup

url = "https://www.jumia.com.ng/mlp-adidas-store"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")


products=soup.find_all("a", class_="core")

In [6]:
print("products=",products)
len(products)

products= [<a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="70.39" data-ga4-index="1" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Women's Fashion" data-ga4-item_category3="Shoes" data-ga4-item_category4="Fashion Sneakers" data-ga4-item_id="AD002FS6B7BZSNAFAMZ" data-ga4-item_name="Levato - Women" data-ga4-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-ga4-price="10.99" data-ga4-tags="CPR_609|CP_20|CP_MT136|CP_MT89|JA|JBF|JF_20|TBOOST|UND_49" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Women's Fashion/Shoes/Fashion Sneakers" data-gtm-dimension23="268872" data-gtm-dimension26="42" data-gtm-dimension27="4.6" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="CPR_609|CP_20|CP_MT136|CP_MT89|JA|JBF|JF_20|TBOOST|UND_49" data-gtm-dimension44="0" data-gtm-id="AD002FS6B7BZSNAFAMZ" data-gtm-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-gtm-name="Levato - Women" data-gtm-position="1" data-gtm-price="10.99" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-levato-women-386941618.html"><div class="-fsh0 -pr -me-start -fw"><img alt="ADIDAS Levato - Women" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/81/6149683/1.jpg?7269" height="185" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="185"/></div><div class="name">ADIDAS Levato - Women</div><div class="prc" data-oprc="₦ 124,500">₦ 16,808</div><div class="bdg _dsct _no-pfx">-87%</div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="70.39" data-ga4-index="2" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Women's Fashion" data-ga4-item_category3="Shoes" data-ga4-item_category4="Fashion Sneakers" data-ga4-item_id="AD002FS6JHOQGNAFAMZ" data-ga4-item_name="Levato - Women" data-ga4-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-ga4-price="10.99" data-ga4-tags="BLF_04|BLF_15|COL_14|COL_171|COL_174|COL_175|COL_178|COL_180|COL_181|COL_183|COL_184|CPR_609|CP_20|CP_23|CP_57|CP_MT136|CP_MT58|CP_MT71|CP_MT89|CP_MT95|CP_UN107|CP_UN109|Camp_100|Camp_11|DOW_5|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_139|TBOOST|TW_40|UND_49" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Women's Fashion/Shoes/Fashion Sneakers" data-gtm-dimension23="268872" data-gtm-dimension26="28" data-gtm-dimension27="4.7" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="BLF_04|BLF_15|COL_14|COL_171|COL_174|COL_175|COL_178|COL_180|COL_181|COL_183|COL_184|CPR_609|CP_20|CP_23|CP_57|CP_MT136|CP_MT58|CP_MT71|CP_MT89|CP_MT95|CP_UN107|CP_UN109|Camp_100|Camp_11|DOW_5|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_139|TBOOST|TW_40|UND_49" data-gtm-dimension44="0" data-gtm-id="AD002FS6JHOQGNAFAMZ" data-gtm-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-gtm-name="Levato - Women" data-gtm-position="2" data-gtm-price="10.99" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-levato-women-386943559.html"><div class="-fsh0 -pr -me-start -fw"><img alt="ADIDAS Levato - Women" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/95/5349683/1.jpg?8046" height="185" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="185"/></div><div class="name">ADIDAS Levato - Women</div><div class="prc" data-oprc="₦ 124,500">₦ 16,808</div><div class="bdg _dsct _no-pfx">-87%</div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="36.33" data-ga4-index="3" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Kid's Fashion" data-ga4-item_category3="Boys" data-ga4-item_category4="Shoes" data-ga4-item_id="AD002FS2M051TNAFAMZ" data-ga4-item_name="Advantage Lifestyle Court Lace Shoes" data-ga4-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-ga4-price="3.67" data-ga4-tags="APWK|BLF_04|BLF_14|COL_184|CPR_596|CPR_609|CP_11|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT36|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT89|Camp_100|Camp_7|Camp_81|DOW_321|DOW_5|DOW_53|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Kid's Fashion/Boys/Shoes" data-gtm-dimension23="268872" data-gtm-dimension26="96" data-gtm-dimension27="4" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="APWK|BLF_04|BLF_14|COL_184|CPR_596|CPR_609|CP_11|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT36|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT89|Camp_100|Camp_7|Camp_81|DOW_321|DOW_5|DOW_53|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-dimension44="0" data-gtm-id="AD002FS2M051TNAFAMZ" data-gtm-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-gtm-name="Advantage Lifestyle Court Lace Shoes" data-gtm-position="3" data-gtm-price="3.67" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-advantage-lifestyle-court-lace-shoes-194409875.html"><div class="-fsh0 -pr -me-start -fw"><img alt="ADIDAS Advantage Lifestyle Court Lace Shoes" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/57/8904491/1.jpg?0570" height="185" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="185"/></div><div class="name">ADIDAS Advantage Lifestyle Court Lace Shoes</div><div class="prc" data-oprc="₦ 61,200">₦ 5,620</div><div class="bdg _dsct _no-pfx">-91%</div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="36.33" data-ga4-index="1" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Kid's Fashion" data-ga4-item_category3="Boys" data-ga4-item_category4="Shoes" data-ga4-item_id="AD002FS2M051TNAFAMZ" data-ga4-item_name="Advantage Lifestyle Court Lace Shoes" data-ga4-list="" data-ga4-price="3.67" data-ga4-tags="APWK|BLF_04|BLF_14|COL_184|CPR_596|CPR_609|CP_11|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT36|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT89|Camp_100|Camp_7|Camp_81|DOW_321|DOW_5|DOW_53|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Kid's Fashion/Boys/Shoes" data-gtm-dimension23="268872" data-gtm-dimension26="96" data-gtm-dimension27="4" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="APWK|BLF_04|BLF_14|COL_184|CPR_596|CPR_609|CP_11|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT36|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT89|Camp_100|Camp_7|Camp_81|DOW_321|DOW_5|DOW_53|INF_93|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-dimension44="0" data-gtm-id="AD002FS2M051TNAFAMZ" data-gtm-list="" data-gtm-name="Advantage Lifestyle Court Lace Shoes" data-gtm-position="1" data-gtm-price="3.67" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-advantage-lifestyle-court-lace-shoes-194409875.html"><div class="img-c"><img alt="ADIDAS Advantage Lifestyle Court Lace Shoes" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/57/8904491/1.jpg?0570" height="208" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="208"/><img alt="JBF" class="_ni camp" data-lazy="true" data-src="https://ng.jumia.is/badges/jbf/1/138x18.png?0075" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></div><div class="info"><div class="bdg _mall _xs">Official Store</div><h3 class="name">ADIDAS Advantage Lifestyle Court Lace Shoes</h3><div class="prc">₦ 5,620</div><div class="s-prc-w"><div class="old">₦ 61,200</div><div class="bdg _dsct _sm">91%</div></div><div class="-df -i-ctr -pvxs"><span class="chip _cpr _sm"><svg class="ic -f-or5 -mrxs" height="12" viewbox="0 0 16 16" width="12"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount"></use></svg><span class="-elli2">Claim Your 10% @ Checkout</span></span><span class="-plm -or5 -m -fs10">+1</span></div><div class="rev"><div class="stars _s">4 out of 5<div class="in" style="width:80%"></div></div>(96)</div><svg aria-label="Express Shipping" class="ic xprss" height="10" viewbox="0 0 114 12" width="94"><use href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express" xlink:href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express"></use></svg></div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="34.49" data-ga4-index="2" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Kid's Fashion" data-ga4-item_category3="Boys" data-ga4-item_category4="Shoes" data-ga4-item_id="AD002FS39V015NAFAMZ" data-ga4-item_name="Advantage Lifestyle Court Lace Shoes Kids" data-ga4-list="" data-ga4-price="5.51" data-ga4-tags="BLF_04|BLF_14|COL_184|CPR_609|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT82|CP_MT89|CP_MT96|Camp_100|Camp_81|Camp_9|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_14|JF_15|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Kid's Fashion/Boys/Shoes" data-gtm-dimension23="268872" data-gtm-dimension26="21" data-gtm-dimension27="3.9" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="BLF_04|BLF_14|COL_184|CPR_609|CP_20|CP_4|CP_MT136|CP_MT14|CP_MT145|CP_MT19|CP_MT42|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT82|CP_MT89|CP_MT96|Camp_100|Camp_81|Camp_9|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_14|JF_15|JF_6|JMALL|TBOOST|xmas_01|xmas_04|xmas_06" data-gtm-dimension44="0" data-gtm-id="AD002FS39V015NAFAMZ" data-gtm-list="" data-gtm-name="Advantage Lifestyle Court Lace Shoes Kids" data-gtm-position="2" data-gtm-price="5.51" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-advantage-lifestyle-court-lace-shoes-kids-194416979.html"><div class="img-c"><img alt="ADIDAS Advantage Lifestyle Court Lace Shoes Kids" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/97/9614491/1.jpg?5264" height="208" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="208"/><img alt="JBF" class="_ni camp" data-lazy="true" data-src="https://ng.jumia.is/badges/jbf/1/138x18.png?0075" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></div><div class="info"><div class="bdg _mall _xs">Official Store</div><h3 class="name">ADIDAS Advantage Lifestyle Court Lace Shoes Kids</h3><div class="prc">₦ 8,430</div><div class="s-prc-w"><div class="old">₦ 61,200</div><div class="bdg _dsct _sm">86%</div></div><div class="-df -i-ctr -pvxs"><span class="chip _cpr _sm"><svg class="ic -f-or5 -mrxs" height="12" viewbox="0 0 16 16" width="12"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount"></use></svg><span class="-elli2">Claim Your 10% @ Checkout</span></span><span class="-plm -or5 -m -fs10">+1</span></div><div class="rev"><div class="stars _s">3.9 out of 5<div class="in" style="width:78%"></div></div>(21)</div><svg aria-label="Express Shipping" class="ic xprss" height="10" viewbox="0 0 114 12" width="94"><use href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express" xlink:href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express"></use></svg></div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="82.56" data-ga4-index="3" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Women's Fashion" data-ga4-item_category3="Shoes" data-ga4-item_category4="Sports Shoes" data-ga4-item_id="AD002FS4UM6HXNAFAMZ" data-ga4-item_name="Court Silk Shoes Women" data-ga4-list="" data-ga4-price="13.19" data-ga4-tags="BLF_04|BLF_15|COL_171|COL_174|COL_178|COL_180|COL_181|COL_182|COL_183|COL_184|CPR_609|CP_20|CP_23|CP_4|CP_MT136|CP_MT14|CP_MT149|CP_MT17|CP_MT42|CP_MT58|CP_MT63|CP_MT71|CP_MT73|CP_MT87|CP_MT88|CP_MT89|CP_MT95|Camp_100|Camp_11|Camp_5|Camp_71|DOW_2|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|TW_21|TW_40|UND_49" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Women's Fashion/Shoes/Sports Shoes" data-gtm-dimension23="268872" data-gtm-dimension26="9" data-gtm-dimension27="4.3" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="BLF_04|BLF_15|COL_171|COL_174|COL_178|COL_180|COL_181|COL_182|COL_183|COL_184|CPR_609|CP_20|CP_23|CP_4|CP_MT136|CP_MT14|CP_MT149|CP_MT17|CP_MT42|CP_MT58|CP_MT63|CP_MT71|CP_MT73|CP_MT87|CP_MT88|CP_MT89|CP_MT95|Camp_100|Camp_11|Camp_5|Camp_71|DOW_2|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_6|JMALL|TBOOST|TW_21|TW_40|UND_49" data-gtm-dimension44="0" data-gtm-id="AD002FS4UM6HXNAFAMZ" data-gtm-list="" data-gtm-name="Court Silk Shoes Women" data-gtm-position="3" data-gtm-price="13.19" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-court-silk-shoes-women-273088239.html"><div class="img-c"><img alt="ADIDAS Court Silk Shoes Women" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/93/2880372/1.jpg?4651" height="208" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="208"/><img alt="JBF" class="_ni camp" data-lazy="true" data-src="https://ng.jumia.is/badges/jbf/1/138x18.png?0075" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></div><div class="info"><div class="bdg _mall _xs">Official Store</div><h3 class="name">ADIDAS Court Silk Shoes Women</h3><div class="prc">₦ 20,180</div><div class="s-prc-w"><div class="old">₦ 146,500</div><div class="bdg _dsct _sm">86%</div></div><div class="-df -i-ctr -pvxs"><span class="chip _cpr _sm"><svg class="ic -f-or5 -mrxs" height="12" viewbox="0 0 16 16" width="12"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount"></use></svg><span class="-elli2">Claim Your 10% @ Checkout</span></span><span class="-plm -or5 -m -fs10">+1</span></div><div class="rev"><div class="stars _s">4.3 out of 5<div class="in" style="width:86%"></div></div>(9)</div><svg aria-label="Express Shipping" class="ic xprss" height="10" viewbox="0 0 114 12" width="94"><use href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express" xlink:href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express"></use></svg></div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="41.98" data-ga4-index="4" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Kid's Fashion" data-ga4-item_category3="Boys" data-ga4-item_category4="Clothing" data-ga4-item_category5="Active" data-ga4-item_id="AD002MW4CX75LNAFAMZ" data-ga4-item_name="Essentials 3-Stripes Woven Tracksuit Bottoms Unisex" data-ga4-list="" data-ga4-price="6.71" data-ga4-tags="BLF_04|BLF_11|BLF_14|COL_184|CPR_609|CP_20|CP_4|CP_MT136|CP_MT19|CP_MT42|CP_MT58|CP_MT63|CP_MT71|CP_MT82|CP_MT89|Camp_100|DOW_259|DOW_295|DOW_5|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_4|TBOOST|ZF_99" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Kid's Fashion/Boys/Clothing/Active" data-gtm-dimension23="268872" data-gtm-dimension26="4" data-gtm-dimension27="5" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="BLF_04|BLF_11|BLF_14|COL_184|CPR_609|CP_20|CP_4|CP_MT136|CP_MT19|CP_MT42|CP_MT58|CP_MT63|CP_MT71|CP_MT82|CP_MT89|Camp_100|DOW_259|DOW_295|DOW_5|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_4|TBOOST|ZF_99" data-gtm-dimension44="0" data-gtm-id="AD002MW4CX75LNAFAMZ" data-gtm-list="" data-gtm-name="Essentials 3-Stripes Woven Tracksuit Bottoms Unisex" data-gtm-position="4" data-gtm-price="6.71" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-essentials-3-stripes-woven-tracksuit-bottoms-unisex-271096536.html"><div class="img-c"><img alt="ADIDAS Essentials 3-Stripes Woven Tracksuit Bottoms Unisex" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/63/5690172/1.jpg?9763" height="208" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="208"/><img alt="JBF" class="_ni camp" data-lazy="true" data-src="https://ng.jumia.is/badges/jbf/1/138x18.png?0075" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></div><div class="info"><div class="bdg _mall _xs">Official Store</div><h3 class="name">ADIDAS Essentials 3-Stripes Woven Tracksuit Bottoms Unisex</h3><div class="prc">₦ 10,265 - ₦ 74,500</div><div class="s-prc-w"><div class="old">₦ 74,500</div><div class="bdg _dsct _sm">86%</div></div><div class="-df -i-ctr -pvxs"><span class="chip _cpr _sm"><svg class="ic -f-or5 -mrxs" height="12" viewbox="0 0 16 16" width="12"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.a8f631ce.svg#discount"></use></svg><span class="-elli2">Claim Your 10% @ Checkout</span></span><span class="-plm -or5 -m -fs10">+1</span></div><div class="rev"><div class="stars _s">5 out of 5<div class="in" style="width:100%"></div></div>(4)</div><svg aria-label="Express Shipping" class="ic xprss" height="10" viewbox="0 0 114 12" width="94"><use href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express" xlink:href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#express"></use></svg></div></a>, <a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="128.54" data-ga4-index="5" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Women's Fashion" data-ga4-item_category3="Shoes" data-ga4-item_category4="Fashion Sneakers" data-ga4-item_id="AD002FS0YA428NAFAMZ" data-ga4-item_name="Originals Sneakers Superstar Slip On W" data-ga4-list="" data-ga4-price="7.76" data-ga4-tags="BLF_04|BLF_15|COL_14|COL_175|COL_178|COL_180|COL_181|COL_183|COL_184|COL_30|CPR_609|CP_20|CP_23|CP_4|CP_MT138|CP_MT149|CP_MT36|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT87|CP_MT88|CP_MT89|CP_MT95|Camp_100|Camp_11|Camp_45|Camp_71|Camp_73|Camp_80|DOW_101|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_107|Merch_187|TBOOST|TW_21|TW_40|UND_49|xmas_01|xmas_04|xmas_06|xmas_12" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Women's Fashion/Shoes/Fashion Sneakers" data-gtm-dimension23="268872" data-gtm-dimension26="2" data-gtm-dimension27="5" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="BLF_04|BLF_15|COL_14|COL_175|COL_178|COL_180|COL_181|COL_183|COL_184|COL_30|CPR_609|CP_20|CP_23|CP_4|CP_MT138|CP_MT149|CP_MT36|CP_MT58|CP_MT63|CP_MT68|CP_MT71|CP_MT87|CP_MT88|CP_MT89|CP_MT95|Camp_100|Camp_11|Camp_45|Camp_71|Camp_73|Camp_80|DOW_101|DOW_5|DOW_53|INV_CLEAR|JA|JBF|JF_6|JMALL|Merch_107|Merch_187|TBOOST|TW_21|TW_40|UND_49|xmas_01|xmas_04|xmas_0

43

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url = "https://www.jumia.com.ng/mlp-adidas-store/"

response = requests.get(url)

print(response.status_code)

200

In [5]:
soup = BeautifulSoup(response.text, "html.parser")
products = soup.find_all("a", class_="core")

print("Number of products:", len(products))

Number of products: 43

In [9]:
first_product = products[0]

print(first_product.prettify())

<a class="core" data-ga4-coupon="CPR_CLAIM_YOUR_10%_@_CHECKOUT" data-ga4-discount="70.39" data-ga4-index="1" data-ga4-is_second_chance="false" data-ga4-item_brand="ADIDAS" data-ga4-item_category="Fashion" data-ga4-item_category2="Women's Fashion" data-ga4-item_category3="Shoes" data-ga4-item_category4="Fashion Sneakers" data-ga4-item_id="AD002FS6B7BZSNAFAMZ" data-ga4-item_name="Levato - Women" data-ga4-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-ga4-price="10.99" data-ga4-tags="CPR_609|CP_20|CP_MT136|CP_MT89|JA|JBF|JF_20|TBOOST|UND_49" data-gtm-brand="ADIDAS" data-gtm-category="Fashion/Women's Fashion/Shoes/Fashion Sneakers" data-gtm-dimension23="268872" data-gtm-dimension26="42" data-gtm-dimension27="4.6" data-gtm-dimension28="1" data-gtm-dimension37="0" data-gtm-dimension43="CPR_609|CP_20|CP_MT136|CP_MT89|JA|JBF|JF_20|TBOOST|UND_49" data-gtm-dimension44="0" data-gtm-id="AD002FS6B7BZSNAFAMZ" data-gtm-list="productfloor_1_mlp:Adidas_Store_20591_en_NG" data-gtm-name="Levato - Women" data-gtm-position="1" data-gtm-price="10.99" data-track-onclick="eecProduct" data-track-onview="eecProduct" data-track-providers="gtm|ga4" href="/adidas-levato-women-386941618.html">
 <div class="-fsh0 -pr -me-start -fw">
  <img alt="ADIDAS Levato - Women" class="img" data-lazy="true" data-src="https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/81/6149683/1.jpg?7269" height="185" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" width="185"/>
 </div>
 <div class="name">
  ADIDAS Levato - Women
 </div>
 <div class="prc" data-oprc="₦ 124,500">
  ₦ 16,808
 </div>
 <div class="bdg _dsct _no-pfx">
  -87%
 </div>
</a>

In [ ]:
Products_Data = []

for product in products:

    product_data = {
        "name": product.get("data-ga4-item_name"),
        "brand": product.get("data-ga4-item_brand"),
        "category": product.get("data-ga4-item_category"),
        "category2": product.get("data-ga4-item_category2"),
        "category3": product.get("data-ga4-item_category3"),
        "category4": product.get("data-ga4-item_category4"),
        "product_id": product.get("data-ga4-item_id"),
        "price": product.get("data-ga4-price"),
        "discount": product.get("data-ga4-discount"),
        "reviews": product.get("data-gtm-dimension26"),
        "rating": product.get("data-gtm-dimension27"),
        "position": product.get("data-gtm-position"),
        "old_price": product.find("div", class_="prc").get("data-oprc")
            if product.find("div", class_="prc") else None
    }

    Products_Data.append(product_data)

df = pd.DataFrame(Products_Data)

df.head()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
df["category4"] = df["category4"].fillna("Unknown")
df["discount"] = df["discount"].fillna("0")
df["old_price"] = df["old_price"].fillna("₦ 0")

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.jumia.com.ng/mlp-adidas-store/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")
products = soup.find_all("a", class_="core")

print("Number of products:", len(products))

Number of products: 43

In [2]:
Products_Data = []

for product in products:

    product_data = {
        "name": product.get("data-ga4-item_name"),
        "brand": product.get("data-ga4-item_brand"),
        "category": product.get("data-ga4-item_category"),
        "category2": product.get("data-ga4-item_category2"),
        "category3": product.get("data-ga4-item_category3"),
        "category4": product.get("data-ga4-item_category4"),
        "product_id": product.get("data-ga4-item_id"),
        "price": product.get("data-ga4-price"),
        "discount": product.get("data-ga4-discount"),
        "reviews": product.get("data-gtm-dimension26"),
        "rating": product.get("data-gtm-dimension27"),
        "position": product.get("data-gtm-position"),
        "old_price": product.find("div", class_="prc").get("data-oprc")
            if product.find("div", class_="prc") else None
    }

    Products_Data.append(product_data)

df = pd.DataFrame(Products_Data)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     str
 8   discount    39 non-null     str
 9   reviews     43 non-null     str
 10  rating      43 non-null     str
 11  position    43 non-null     str
 12  old_price   3 non-null      str
dtypes: str(13)
memory usage: 4.5 KB

In [3]:
df["category4"] = df["category4"].fillna("Unknown")
df["discount"] = df["discount"].fillna("0")
df["old_price"] = df["old_price"].fillna("₦ 0")

In [4]:
df.isnull().sum()

name          0
brand         0
category      0
category2     0
category3     0
category4     0
product_id    0
price         0
discount      0
reviews       0
rating        0
position      0
old_price     0
dtype: int64

In [5]:
df = pd.DataFrame(Products_Data)

In [7]:
numeric_columns = [
    "price",
    "old_price",
    "discount",
    "reviews",
    "rating",
    "position"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column].astype(str).str.replace("₦", "", regex=False).str.replace(",", "", regex=False),
        errors="coerce"
    )
    df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        43 non-null     str
 1   brand       43 non-null     str
 2   category    43 non-null     str
 3   category2   43 non-null     str
 4   category3   43 non-null     str
 5   category4   42 non-null     str
 6   product_id  43 non-null     str
 7   price       43 non-null     float64
 8   discount    39 non-null     float64
 9   reviews     37 non-null     float64
 10  rating      37 non-null     float64
 11  position    43 non-null     int64
 12  old_price   3 non-null      float64
dtypes: float64(5), int64(1), str(7)
memory usage: 4.5 KB

In [8]:
df.isnull().sum()

name           0
brand          0
category       0
category2      0
category3      0
category4      1
product_id     0
price          0
discount       4
reviews        6
rating         6
position       0
old_price     40
dtype: int64

In [9]:
df["category4"] = df["category4"].fillna("Unknown")

df["discount"] = df["discount"].fillna(0)

df["reviews"] = df["reviews"].fillna(0)

df["rating"] = df["rating"].fillna(df["rating"].median())

df["old_price"] = df["old_price"].fillna(0)

df.isnull().sum()

name          0
brand         0
category      0
category2     0
category3     0
category4     0
product_id    0
price         0
discount      0
reviews       0
rating        0
position      0
old_price     0
dtype: int64

In [10]:
df[["price", "old_price", "discount", "reviews", "rating"]].describe()

           price      old_price   discount    reviews     rating
count  43.000000      43.000000   43.00000  43.000000  43.000000
mean   12.684884    7213.953488   36.56000  10.976744   4.616279
std    18.421837   27820.928927   22.01951  21.215996   0.512199
min     3.570000       0.000000    0.00000   0.000000   3.200000
25%     5.160000       0.000000   22.26000   1.000000   4.150000
50%     7.320000       0.000000   36.03000   4.000000   4.900000
75%     9.340000       0.000000   47.44500  11.000000   5.000000
max    95.470000  124500.000000  103.36000  97.000000   5.000000

In [11]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 5.16
Q3: 9.34
IQR: 4.18
Lower bound: -1.1099999999999994
Upper bound: 15.61

In [12]:
outliers = df[(df["price"] < lower_bound) | (df["price"] > upper_bound)]

outliers[["name", "price"]]

                                                 name  price
10  Grand Court Cloudfoam Lifestyle Court Comfort ...  18.24
11  Grand Court TD Lifestyle Court Casual Shoes Women  95.47
21             Classic Badge Of Sport Backpack Unisex  37.25
31  Grand Court Elastic Lace And Top Strap Shoes U...  67.18
34  POWERREACT TRAINING MEDIUM-SUPPORT TECHFIT BRA...  60.37

In [13]:
df_clean = df.copy()
df_clean = df_clean[
    (df_clean["price"] >= lower_bound) &
    (df_clean["price"] <= upper_bound)
]

print("Original rows:", len(df))
print("Rows after outlier removal:", len(df_clean))

Original rows: 43
Rows after outlier removal: 38

In [14]:
df_clean[["name", "price"]].head()

                                        name  price
0                             Levato - Women  12.22
1                             Levato - Women  12.22
2       Advantage Lifestyle Court Lace Shoes   4.00
3       Advantage Lifestyle Court Lace Shoes   4.01
4  Advantage Lifestyle Court Lace Shoes Kids   6.01

In [15]:
df_clean = df_clean[
    (df_clean["price"] >= lower_bound) &
    (df_clean["price"] <= upper_bound)
]

df_clean[["brand", "category", "category2", "category3", "category4"]].nunique()

brand        1
category     2
category2    4
category3    5
category4    7
dtype: int64

In [16]:
categorical_columns = [
    "category",
    "category2",
    "category3",
    "category4"
]

df_encoded = pd.get_dummies(
    df_clean,
    columns=categorical_columns,
    dtype=int
)

df_encoded.head()
df_encoded.shape

(38, 27)